// <auto-generated />
using System;
using GestionGuarderiaBackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionGuarderiaBackEnd.Migrations
{
    [DbContext(typeof(DatosDbContext))]
    [Migration("20250919231619_Update-Models")]
    partial class UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AsignacionModelNinoModel", b =>
                {
                    b.Property<int>("NinoId")
                        .HasColumnType("int");

                    b.Property<int>("NinosNinoId")
                        .HasColumnType("int");

                    b.HasKey("NinoId", "NinosNinoId");

                    b.HasIndex("NinosNinoId");

                    b.ToTable("AsignacionModelNinoModel");
                });

            modelBuilder.Entity("GestionGuarderiaBackEnd.Models.Entidades.AsignacionModel", b =>
                {
                    b.Property<int>("AsignacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AsignacionId"));

                    b.Property<int>("CuidadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NinoId")
                        .HasColumnType("int");

                    b.HasKey("AsignacionId");

                    b.HasIndex("CuidadorId");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("GestionGuarderiaBackEnd.Models.Entidades.CuidadorModel", b =>
                {
                    b.Property<int>("CuidadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CuidadorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CuidadorId");

                    b.ToTable("Cuidadores");
                });

            modelBuilder.Entity("GestionGuarderiaBackEnd.Models.Entidades.NinoModel", b =>
                {
                    b.Property<int>("NinoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NinoId"));

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NinoId");

                    b.ToTable("Ninos");
                });

            modelBuilder.Entity("AsignacionModelNinoModel", b =>
                {
                    b.HasOne("GestionGuarderiaBackEnd.Models.Entidades.AsignacionModel", null)
                        .WithMany()
                        .HasForeignKey("NinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionGuarderiaBackEnd.Models.Entidades.NinoModel", null)
                        .WithMany()
                        .HasForeignKey("NinosNinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionGuarderiaBackEnd.Models.Entidades.AsignacionModel", b =>
                {
                    b.HasOne("GestionGuarderiaBackEnd.Models.Entidades.CuidadorModel", "Cuidador")
                        .WithMany("Asignaciones")
                        .HasForeignKey("CuidadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuidador");
                });

            modelBuilder.Entity("GestionGuarderiaBackEnd.Models.Entidades.CuidadorModel", b =>
                {
                    b.Navigation("Asignaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
